In [1]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 3))
print("1. Исходная матрица (3x3):\n", matrix)

det = np.linalg.det(matrix)
print("\n2. Определитель матрицы:", det)

if np.isclose(det, 0):
    print("\n3. Матрица вырождена, обратной матрицы не существует.")
else:
    inv_matrix = np.linalg.inv(matrix)
    print("\n3. Обратная матрица:\n", inv_matrix)

1. Исходная матрица (3x3):
 [[4 9 8]
 [2 4 9]
 [1 9 3]]

2. Определитель матрицы: -137.00000000000003

3. Обратная матрица:
 [[ 0.50364964 -0.32846715 -0.35766423]
 [-0.02189781 -0.02919708  0.1459854 ]
 [-0.10218978  0.19708029  0.01459854]]
