In [3]:
import numpy as np

A = np.array([
    [2, 3, -1],
    [4, -1, 2],
    [-3, 5, 4]
])

B = np.array([5, 6, -2])

print("1. Матрица коэффициентов A:\n", A)
print("\n2. Вектор правой части B:", B)

X = np.linalg.solve(A, B)

print("\n3. Решение системы (вектор X):")
print("   x =", X[0])
print("   y =", X[1])
print("   z =", X[2])

1. Матрица коэффициентов A:
 [[ 2  3 -1]
 [ 4 -1  2]
 [-3  5  4]]

2. Вектор правой части B: [ 5  6 -2]

3. Решение системы (вектор X):
   x = 1.6396396396396398
   y = 0.5765765765765767
   z = 0.009009009009008993
