In [6]:
import numpy as np

print("Исходный массив:\n", matrix)

matrix = matrix * 2
print("\nПосле умножения на 2:\n", matrix)

matrix[matrix > 10] = 0

print("\nИтоговый массив (элементы > 10 заменены на 0):\n", matrix)

Исходный массив:
 [[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]

После умножения на 2:
 [[ 4  8 12]
 [16 20  0]
 [ 0  0  0]]

Итоговый массив (элементы > 10 заменены на 0):
 [[4 8 0]
 [0 0 0]
 [0 0 0]]
