In [1]:
import numpy as np

arr1 = np.random.randint(0, 51, size=(1, 5))
arr2 = np.random.randint(0, 51, size=(1, 5))

print("1. Первый массив (1x5):\n", arr1)
print("   Второй массив (1x5):\n", arr2)

combined_matrix = np.vstack((arr1, arr2))
print("\n2. Объединенный двумерный массив (по строкам, 2x5):\n", combined_matrix)

split_arrays = np.vsplit(combined_matrix, 2)

print("\n3. Результат разделения:")
print("   Первый разделенный массив:\n", split_arrays[0])
print("   Второй разделенный массив:\n", split_arrays[1])

1. Первый массив (1x5):
 [[14 42 31 12 28]]
   Второй массив (1x5):
 [[41 45 45 45  8]]

2. Объединенный двумерный массив (по строкам, 2x5):
 [[14 42 31 12 28]
 [41 45 45 45  8]]

3. Результат разделения:
   Первый разделенный массив:
 [[14 42 31 12 28]]
   Второй разделенный массив:
 [[41 45 45 45  8]]
