In [1]:
import numpy as np

identity_matrix = np.eye(4)
print("1. Единичная матрица 4x4:\n", identity_matrix)

diagonal_elements = [5, 10, 15, 20]
diagonal_matrix = np.diag(diagonal_elements)
print("\n2. Диагональная матрица 4x4:\n", diagonal_matrix)

sum_identity = np.sum(identity_matrix)
sum_diagonal = np.sum(diagonal_matrix)

print("\n3. Сравнение сумм элементов:")
print("   Сумма элементов единичной матрицы:", sum_identity)
print("   Сумма элементов диагональной матрицы:", sum_diagonal)

if sum_identity > sum_diagonal:
    print("   Результат: Сумма единичной матрицы больше")
elif sum_identity < sum_diagonal:
    print("   Результат: Сумма диагональной матрицы больше")
else:
    print("   Результат: Суммы равны")

1. Единичная матрица 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

2. Диагональная матрица 4x4:
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]

3. Сравнение сумм элементов:
   Сумма элементов единичной матрицы: 4.0
   Сумма элементов диагональной матрицы: 50
   Результат: Сумма диагональной матрицы больше
