In [1]:
import numpy as np

matrix_1 = np.random.randint(1, 11, size=(2, 3))
matrix_2 = np.random.randint(1, 11, size=(3, 2))

print("1. Первая матрица (2x3):\n", matrix_1)
print("\n2. Вторая матрица (3x2):\n", matrix_2)

matrix_dot_product = matrix_1 @ matrix_2

print("\n3. Результат матричного умножения (2x2):\n", matrix_dot_product)

1. Первая матрица (2x3):
 [[8 6 1]
 [5 1 6]]

2. Вторая матрица (3x2):
 [[ 7  6]
 [ 4  5]
 [10 10]]

3. Результат матричного умножения (2x2):
 [[90 88]
 [99 95]]
