In [1]:
import numpy as np

matrix_A = np.random.randint(1, 21, size=(3, 3))
matrix_B = np.random.randint(1, 21, size=(3, 3))

print("1. Матрица A (3x3):\n", matrix_A)
print("\n2. Матрица B (3x3):\n", matrix_B)

matrix_sum = matrix_A + matrix_B
matrix_diff = matrix_A - matrix_B
matrix_elementwise_prod = matrix_A * matrix_B

print("\n3. Результаты операций:")
print("   Сумма матриц:\n", matrix_sum)
print("\n   Разность матриц:\n", matrix_diff)
print("\n   Поэлементное произведение:\n", matrix_elementwise_prod)

1. Матрица A (3x3):
 [[10  5  4]
 [13 17  5]
 [18 16 14]]

2. Матрица B (3x3):
 [[ 4 12  2]
 [13  8  8]
 [14 13 14]]

3. Результаты операций:
   Сумма матриц:
 [[14 17  6]
 [26 25 13]
 [32 29 28]]

   Разность матриц:
 [[ 6 -7  2]
 [ 0  9 -3]
 [ 4  3  0]]

   Поэлементное произведение:
 [[ 40  60   8]
 [169 136  40]
 [252 208 196]]
