In [3]:
import numpy as np

matrix = np.random.randint(1, 51, size=(4, 4))
print("1. Исходная матрица (4x4):\n", matrix)

transposed_matrix = matrix.T
print("\n2. Транспонированная матрица:\n", transposed_matrix)

matrix_trace = np.trace(matrix)
print("\n3. След матрицы (сумма элементов главной диагонали):", matrix_trace)

1. Исходная матрица (4x4):
 [[20 21 39 49]
 [33 47 26 45]
 [ 3 28 35 30]
 [18 12  4 16]]

2. Транспонированная матрица:
 [[20 33  3 18]
 [21 47 28 12]
 [39 26 35  4]
 [49 45 30 16]]

3. След матрицы (сумма элементов главной диагонали): 118
